"""Initial migration

Revision ID: fd22f916fd75
Revises: 
Create Date: 2025-03-01 00:05:35.362252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd22f916fd75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('Orderitem',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('Review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.drop_table('orderitem')
    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('review')
    op.alter_column('Order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('Order_user_id_fkey', 'Order', type_='foreignkey')
    op.create_foreign_key(None, 'Order', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.create_foreign_key('Order_user_id_fkey', 'Order', 'User', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('Order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('review',
    sa.Column('review_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='review_rating_check'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name='review_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='review_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', name='review_pkey')
    )
    op.create_table('category',
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text("nextval('category_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), server_default=sa.text("nextval('product_product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('price >= 0::numeric', name='product_price_check'),
    sa.CheckConstraint('stock >= 0', name='product_stock_check'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='product_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orderitem',
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('price >= 0::numeric', name='orderitem_price_check'),
    sa.CheckConstraint('quantity > 0', name='orderitem_quantity_check'),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], name='orderitem_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name='orderitem_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', name='orderitem_pkey')
    )
    op.drop_table('Review')
    op.drop_table('Orderitem')
    op.drop_table('Product')
    op.drop_table('Category')
    # ### end Alembic commands ###
